ccflags-y += -Idrivers/media/platform/msm/camera_oneplus/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_oneplus/cam_smmu/
ccflags-y += -Idrivers/media/platform/msm/camera_oneplus/cam_sync
ccflags-y += -Idrivers/media/platform/msm/camera_oneplus/cam_utils

obj-$(CONFIG_SPECTRA_CAMERA) += cam_context.o cam_context_utils.o cam_node.o cam_subdev.o
