ccflags-y += -Idrivers/media/platform/msm/camera_oneplus/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_oneplus/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_oneplus/cam_sensor_module/cam_sensor_io
ccflags-y += -Idrivers/media/platform/msm/camera_oneplus/cam_sensor_module/cam_cci
ccflags-y += -Idrivers/media/platform/msm/camera_oneplus/cam_sensor_module/cam_res_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_oneplus/cam_smmu/

obj-$(CONFIG_SPECTRA_CAMERA) +=  cam_sensor_util.o
